<a href="https://colab.research.google.com/github/ayushithakurr686-commits/Numpy-/blob/main/Class1file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np
l =[10,20,30,40,50]  #1 Dimentional array
array = np.array(l)
print(array)

[10 20 30 40 50]


In [ ]:
a =[[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(a)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

Lets create a matrix using list

In [ ]:
a =[[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(a)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
#np.zeros() for 1D
zeros = np.zeros(8)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#np.zeros() for matrix
#rows and columns
np.zeros([3,4]) #rows,columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(6)


array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full(5,6)

array([6, 6, 6, 6, 6])

In [ ]:
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
#np.arrange
arr = np.arange(0,11,2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [4]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#np.linspace() #start = 0, stop =1, value =5
np.linspace (0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#np.random.rand() #rows,columns
np.random.rand(2,3)

array([[0.11801347, 0.01693281, 0.89687794],
       [0.90167865, 0.71692465, 0.12046353]])

In [ ]:
#np.random.randint(start,stop,(rows,columns))

np.random.randint(1,20,(3,3))


# """
# randint -> 1 se 20 ke beech ki random values se
# matrix create karega
# """

array([[ 3,  5,  8],
       [14, 14, 13],
       [16,  2, 17]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution