<a href="https://colab.research.google.com/github/ayushithakurr686-commits/Numpy-/blob/main/class3file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [2]:
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3])

#1 addition
print(a+b)

#2 substraction
print(a-b)

#3 Multiplication
print(a*b)

[11 22 33]
[ 9 18 27]
[10 40 90]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
a = np.array([10,20,30])
print(a*5)

[ 50 100 150]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
#Basic Statistical operation perform
arr = np.array([4,78,21,34,100,56])
#1.sum
print(f"Sum is ; {arr.sum()}")

#2.Mean
print(f"Mean (Average) is: {arr.mean()}")


#3. Min
print(f"Min is: {arr.min()}")

#4. Max
print(f"Max is: {arr.max()}")


#4.Max
print(f"Max is: {arr.max()}")

#5.Standard deviation
print(f"Standard deviation is: {arr.std()}")

#6. Varaince
print(f"Variance is: {arr.var()}")



Sum is ; 293
Mean (Average) is: 48.833333333333336
Min is: 4
Max is: 100
Max is: 100
Standard deviation is: 32.97684372741306
Variance is: 1087.4722222222224


You can also do the axis based operations row-Wise and Colum-wise

In [3]:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(f"Sum of all: {data.sum()}")

#axis = 0 -> columns
#axis = 1 -> rows
print(f"Sum of columns : {np.sum(data, axis = 0)}")
print(f"Sum of rows : {np.sum(data, axis = 1)}")

Sum of all: 45
Sum of columns : [12 15 18]
Sum of rows : [ 6 15 24]
